/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;



import ConexionSerial.ConexionSerialJrIng;
import gnu.io.PortInUseException;
import gnu.io.UnsupportedCommOperationException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class tablero extends javax.swing.JFrame {

    
    
    ConexionSerialJrIng Serial;
    
    public tablero() throws PortInUseException, UnsupportedCommOperationException, IOException {
        initComponents();
         llenarTabla();
        Serial = new ConexionSerialJrIng(9600, "COM11");
        
        new Thread(new Runnable(){
            @Override
            public void run(){
         
                String mensaje = "";
                
                while(true){
                    mensaje = Serial.SerialRead();
                    
                    if(mensaje != ""){
                        jLabel2.setText(mensaje);
                        mensaje = "";
                    }
                }
                
                
            }
        }).start();
    
    
    
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        mostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInfo.setBackground(new java.awt.Color(255, 255, 153));
        tblInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblInfo.setForeground(new java.awt.Color(102, 0, 255));
        tblInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "B", "I", "N", "G", "O"
            }
        ));
        tblInfo.setFocusable(false);
        tblInfo.setGridColor(new java.awt.Color(153, 0, 255));
        tblInfo.setSelectionBackground(new java.awt.Color(255, 102, 255));
        jScrollPane1.setViewportView(tblInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 770, 270));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jButton1.setText("Jugar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 260, 120, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 200, 80));

        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tablero5.jpg"))); // NOI18N
        getContentPane().add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, -1, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   private void llenarTabla(){
    
         try{

        String[] columna = { "B","I","N","G","O"};
            DefaultTableModel dtm = new DefaultTableModel(null,columna);
         //  ArrayList<RegistroEmpleado> Lista= datos.todosLosEmpleados();
          
            int B=0,I=0,N=0,G=0,O = 0;
           // for (RegistroEmpleado est : Lista)
          for(int i = 1;i<16;i++)  {  
              
               
               for(int o = 1;o<6;o++)  { 
                   int numero_random = (int) Math.floor(Math.random()*75+1);
                   if(o == 1){
                      B = numero_random;
                   }
                   if(o == 2){
                      I = numero_random;
                   }
                   if(o == 3){
                      N = numero_random;
                   }
                   if(o == 4){
                      G = numero_random;
                   }
                   if(o == 5){
                      O = numero_random;
                   }
                   
                
               }
               
                String[] row = {String.valueOf(B),String.valueOf(I),String.valueOf(N),String.valueOf(G),String.valueOf(O)};
                dtm.addRow(row);
                
            }
            
            tblInfo.setModel(dtm);
            
            
    }catch(Exception e){
        
    }

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new tablero().setVisible(true);
                } catch (PortInUseException ex) {
                    Logger.getLogger(tablero.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedCommOperationException ex) {
                    Logger.getLogger(tablero.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(tablero.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mostrar;
    private javax.swing.JTable tblInfo;
    // End of variables declaration//GEN-END:variables
}
